---
-
  name: "Converge"
  hosts: "all"
  tasks:
    -
      name: "Include cornfeedhobo.postfix"
      ansible.builtin.include_role:
        name: "cornfeedhobo.postfix"
      vars:
        postfix_install: true
        postfix_configure: true
        postfix_aliases:
          root: "user1, user2"
